<?php 
$cate_nam_lists = [
    [
        'slug'=>'us',
        'current'=>'curr1',
    ],
    [
        'slug'=>'england',
        'current'=>'curr2',
    ],
    [
        'slug'=>'italy',
        'current'=>'curr3',
    ],
    [
        'slug'=>'espana',
        'current'=>'curr4',
    ],
    [
        'slug'=>'coronbia',
        'current'=>'curr5',
    ],
    [
        'slug'=>'peru',
        'current'=>'curr6',
    ],
    [
        'slug'=>'alzentin',
        'current'=>'curr7',
    ],
    [
        'slug'=>'espana',
        'current'=>'curr8',
    ],
    [
        'slug'=>'dovai',
        'current'=>'curr9',
    ],
    [
        'slug'=>'marasia',
        'current'=>'curr10',
    ],
    [
        'slug'=>'moroko',
        'current'=>'curr11',
    ],
    [
        'slug'=>'osutraria',
        'current'=>'curr12',
    ],
    [
        'slug'=>'canada',
        'current'=>'curr13',
    ],
    [
        'slug'=>'aruzenntinn',
        'current'=>'curr14',
    ],
    [
        'slug'=>'mekisyco',
        'current'=>'curr15',
    ],
    [
        'slug'=>'nyujiland',
        'current'=>'curr16',
    ],
    [
        'slug'=>'belgi',
        'current'=>'curr17',
    ],
    [
        'slug'=>'monngoru',
        'current'=>'curr18',
    ],
    [
        'slug'=>'flance',
        'current'=>'curr19',
    ],
    [
        'slug'=>'losia',
        'current'=>'curr20',
    ],
    [
        'slug'=>'ukuraia',
        'current'=>'curr21',
    ],
    [
        'slug'=>'toluco',
        'current'=>'curr22',
    ],
    [
        'slug'=>'ejiput',
        'current'=>'curr23',
    ],
    [
        'slug'=>'noluwee',
        'current'=>'curr24',
    ],
    [
        'slug'=>'girisha',
        'current'=>'curr25',
    ],
    [
        'slug'=>'kuroatia',
        'current'=>'curr26',
    ],
    [
        'slug'=>'kannkoku',
        'current'=>'curr27',
    ],
    [
        'slug'=>'kazafusutan',
        'current'=>'curr28',
    ],
    [
        'slug'=>'tiri',
        'current'=>'curr29',
    ],
];
;?>